globalThis.DEV_TOOLS_CATALOG = Object.freeze([
  {
    id: "base-converter",
    name: "Base Converter",
    route: "base-converter",
    description: "Convert UTF-8 text and byte values between binary, hexadecimal, decimal, and octal representations instantly in your browser.",
    capabilities: ["UTF-8 text and byte conversion", "Binary, hexadecimal, decimal, and octal output", "Live bidirectional conversion"],
  },
  {
    id: "bcrypt-generator",
    name: "Bcrypt Hash Generator",
    route: "bcrypt-generator",
    description: "Hash passwords with bcrypt at a chosen cost and verify a password against any $2a$, $2b$, or $2y$ hash, entirely in your browser.",
    capabilities: ["Bcrypt hashing with cost 4–15 and $2a$/$2b$/$2y$ prefixes", "Password verification against an existing hash", "Hash anatomy and 72-byte limit warnings"],
  },
  {
    id: "certificate-decoder",
    name: "Certificate Decoder",
    route: "certificate-decoder",
    description: "Decode PEM certificates, chains, CSRs, and public keys to see the issuer, SANs, expiry, key details, and fingerprints, entirely in your browser.",
    capabilities: ["X.509 certificate and chain decoding", "Expiry status, SANs, and key usage", "Fingerprints, SPKI pins, and chain signature checks"],
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    route: "chmod-calculator",
    description: "Build Unix file permissions from a checkbox grid and read the octal, symbolic, chmod command, and umask defaults at once.",
    capabilities: ["Octal, symbolic, and checkbox editing", "Ready-to-run chmod and umask commands", "Plain-English reading with risk warnings"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    route: "color-converter",
    description: "Convert colours between HEX, RGB, HSL, and OKLCH and check any pair against the WCAG contrast thresholds, entirely in your browser.",
    capabilities: ["HEX, RGB, HSL, and OKLCH conversion", "WCAG AA and AAA contrast ratios", "Alpha compositing and sRGB gamut warnings"],
  },
  {
    id: "cron-expression-generator",
    name: "Cron Expression Generator",
    route: "cron-expression-generator",
    description: "Build, parse, and explain cron expressions in plain English, then preview the next scheduled run times in any time zone.",
    capabilities: ["Plain-English schedule explanation", "Next run times in any time zone", "Per-field editor with common presets"],
  },
  {
    id: "crypto-generator",
    name: "Crypto Generator",
    route: "crypto-generator",
    description: "Generate cryptographically secure random values and developer-friendly credentials locally with your browser's security APIs.",
    capabilities: ["Cryptographically secure randomness", "Developer-friendly output formats", "Local browser generation"],
  },
  {
    id: "csv-json-converter",
    name: "CSV ⇄ JSON Converter",
    route: "csv-json-converter",
    description: "Convert CSV to JSON and JSON back to CSV with delimiter auto-detection and type inference, and browse the data as a sortable table.",
    capabilities: ["CSV-to-JSON and JSON-to-CSV conversion", "Delimiter auto-detection and type inference", "Sortable, filterable table viewer"],
  },
  {
    id: "docker-compose-converter",
    name: "Docker Run to Compose Converter",
    route: "docker-compose-converter",
    description: "Convert docker run commands into a docker-compose.yml with ports, volumes, environment, networks, healthchecks, and limits mapped, locally in your browser.",
    capabilities: ["Multiple docker run commands to one compose file", "Volumes, networks, healthchecks, GPUs, and resource limits", "Notes for every flag without a Compose equivalent"],
  },
  {
    id: "encoder-decoder",
    name: "Encoder / Decoder",
    route: "encoder-decoder",
    description: "Encode and decode text with Base64, Base64url, URL percent-encoding, and HTML entities, and turn files into Base64 or data: URIs and back, locally in your browser.",
    capabilities: ["Base64 and Base64url encoding", "URL component and full-URL escaping", "HTML entity escaping and unescaping", "File to Base64 and data: URI conversion with preview"],
  },
  {
    id: "env-json-shell-converter",
    name: ".env ⇄ JSON ⇄ Shell Converter",
    route: "env-json-shell-converter",
    description: "Convert environment variables between .env files, JSON objects, and shell export lines for Bash, fish, and PowerShell, locally in your browser.",
    capabilities: [".env, JSON, and shell export in any direction", "Bash, fish, and PowerShell output with safe quoting", "${VAR} expansion, multiline values, and Kubernetes-style env lists"],
  },
  {
    id: "fake-data-generator",
    name: "Fake Data Generator",
    route: "fake-data-generator",
    description: "Design a schema and generate realistic JSON test records with names, addresses, IDs, dates, numbers, and nested fields.",
    capabilities: ["Visual schema builder", "Realistic test-data fields", "Flat and nested JSON records"],
  },
  {
    id: "file-compressor",
    name: "File Compressor",
    route: "file-compressor",
    description: "Compress files locally in your browser with multiple algorithms while comparing original and compressed sizes before download.",
    capabilities: ["Multiple compression formats", "Before-and-after size comparison", "Local file processing"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    route: "hash-generator",
    description: "Compute MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes and HMACs of text or files, and check them against an expected checksum, entirely in your browser.",
    capabilities: ["MD5, SHA-1, SHA-256, SHA-384, and SHA-512 digests", "HMAC with UTF-8, hex, or Base64 keys", "File hashing and checksum comparison"],
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    route: "html-preview",
    description: "Write HTML, CSS, and JavaScript in a live browser playground with an instant preview and downloadable output.",
    capabilities: ["Live HTML, CSS, and JavaScript editing", "Instant isolated preview", "Downloadable result"],
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    route: "http-status-codes",
    description: "Search every HTTP status code with plain-English meanings, when-to-use guidance, common mistakes, and the RFC that defines it.",
    capabilities: ["Searchable 1xx-5xx reference", "When to use and what to avoid", "RFC references and related codes"],
  },
  {
    id: "image-toolkit",
    name: "Image Toolkit",
    route: "image-toolkit",
    description: "Convert PNG, JPEG, WebP, SVG, and BMP images locally, generate a full favicon and app-icon pack with its manifest, and optimize SVG markup — all in the browser.",
    capabilities: [
      "Automatic source-format detection",
      "PNG, JPEG, and WebP output",
      "Optional metadata stripping",
      "Favicon and app-icon pack with manifest",
      "SVG optimization with size report",
    ],
  },
  {
    id: "id-generator",
    name: "ID Generator",
    route: "id-generator",
    description: "Generate and inspect developer identifiers including UUID variants and ULIDs directly in your browser.",
    capabilities: ["Multiple UUID versions", "ULID generation", "Identifier decoding and inspection"],
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    route: "json-diff",
    description: "Compare two JSON documents with formatting, validation, and clear structural difference highlighting.",
    capabilities: ["Side-by-side JSON comparison", "Syntax validation and formatting", "Structural difference highlighting"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Query",
    route: "json-formatter",
    description: "Format, minify, and sort JSON without reordering keys or rounding big numbers, then query it with JSONPath or jq, all in your browser.",
    capabilities: ["Pretty, minified, and sorted-key output", "Key order and number literals preserved", "JSONPath and jq query tester"],
  },
  {
    id: "json-toon-converter",
    name: "JSON ⇄ Toon Converter",
    route: "json-toon-converter",
    favicon: "favicon-json-toon.svg",
    // The reverse direction used to be its own listing; its old route and id
    // still resolve, opening this tool in Toon → JSON mode.
    aliases: [{ id: "toon-json-converter", route: "toon-to-json-converter", hash: "#toon-json" }],
    description: "Convert JSON to compact Toon format and Toon back to JSON locally, with validation, token savings, and copy-ready output.",
    capabilities: ["JSON-to-Toon and Toon-to-JSON conversion", "Input validation", "Token reduction statistics"],
  },
  {
    id: "json-xml-converter",
    name: "JSON ⇄ XML Converter",
    route: "json-to-xml-converter",
    favicon: "favicon-json-xml.svg",
    aliases: [{ id: "xml-json-converter", route: "xml-to-json-converter", hash: "#xml-json" }],
    description: "Convert JSON documents to formatted XML and XML back to readable JSON locally, with validation and editing controls.",
    capabilities: ["JSON-to-XML and XML-to-JSON conversion", "Syntax validation", "Formatted XML and JSON output"],
  },
  {
    id: "json-yaml-toml-converter",
    name: "JSON ⇄ YAML ⇄ TOML Converter",
    route: "json-yaml-toml-converter",
    description: "Convert between JSON, YAML, and TOML in any direction — Kubernetes manifests, CI configs, Cargo and pyproject files — locally in your browser.",
    capabilities: ["JSON, YAML, and TOML in any direction", "Multi-document YAML support", "Validation with line-level error messages"],
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    route: "jwt-debugger",
    description: "Decode, inspect, edit, and verify JSON Web Tokens with readable header, payload, signature, and timestamp details.",
    capabilities: ["JWT header and payload decoding", "Signature verification tools", "Claim and timestamp inspection"],
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    route: "lorem-ipsum-generator",
    toolPath: "text-utilities",
    endpoint: "#lorem",
    favicon: "favicon-lorem.svg",
    description: "Generate lorem ipsum placeholder paragraphs, sentences, words, or list items locally and count them as you go.",
    capabilities: ["Paragraph, sentence, word, and list output", "Classic Lorem ipsum opening", "Instant word and character counts"],
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    route: "markdown-editor",
    description: "Write Markdown with synchronized editing, safe live preview, local file opening, and export-friendly controls.",
    capabilities: ["Safe live Markdown preview", "Local file opening", "Synchronized editor experience"],
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    route: "qr-generator",
    description: "Create customizable QR codes for links, contact details, Wi-Fi, email, phone, UPI, and other common formats.",
    capabilities: ["Multiple QR content types", "Customizable output", "Downloadable QR codes"],
  },
  {
    id: "regex-cheatsheet",
    name: "Regex Cheat Sheet",
    route: "regex-cheatsheet",
    description: "A JavaScript regex reference with syntax, flags, lookaround, and a library of tested patterns for email, URL, UUID, and more.",
    capabilities: ["Searchable ECMAScript syntax reference", "Tested pattern library with samples", "One-click handover to the Regex Tester"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    route: "regex-tester",
    description: "Test regular expressions with live match highlighting, flags, capture details, navigation, and replacement templates.",
    capabilities: ["Live regular-expression matches", "Flag and capture-group controls", "Replacement output templates"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    route: "sql-formatter",
    description: "Format and beautify SQL queries locally with readable indentation and practical editor controls.",
    capabilities: ["SQL formatting and beautification", "Readable indentation", "Local query processing"],
  },
  {
    id: "string-escaper",
    name: "Slug Generator / String Escaper",
    route: "string-escaper",
    description: "Generate URL slugs and escape or unescape strings for JSON, SQL, shell, regex, and HTML attributes locally in your browser.",
    capabilities: ["URL slugs with transliteration and length limits", "JSON, SQL, shell, regex, and HTML attribute escaping", "Unescaping literals back to plain text"],
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    route: "subnet-calculator",
    description: "Calculate IPv4 and IPv6 subnets from CIDR notation: network, broadcast, netmask, usable host range, and address type, then split blocks and convert ranges to CIDR.",
    capabilities: ["IPv4 and IPv6 CIDR and netmask breakdown", "Subnet splitting by prefix or host count", "Address containment and range-to-CIDR conversion"],
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    route: "text-case-converter",
    description: "Convert text into camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and Title Case at once, with a line-by-line bulk mode.",
    capabilities: ["Six identifier styles converted at once", "Camel, Pascal, snake, kebab, constant, and title case", "Bulk mode converts each line independently"],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    route: "text-cleaner",
    toolPath: "text-utilities",
    endpoint: "#clean",
    description: "Trim, sort, deduplicate, renumber, and recase lines of text locally with a predictable, ordered pipeline.",
    capabilities: ["Trim, collapse, and drop empty lines", "Sort, reverse, shuffle, and deduplicate", "Upper, lower, title, and sentence case"],
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    route: "timestamp-converter",
    description: "Convert Unix timestamps to ISO 8601, human-readable and relative time across time zones, and back again, entirely in your browser.",
    capabilities: ["Unix seconds, milliseconds and microseconds", "ISO 8601, RFC 1123 and relative time", "Time zone and DST aware conversion"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    route: "text-diff",
    description: "Compare text side by side with added, removed, modified, and character-level differences clearly highlighted.",
    capabilities: ["Side-by-side text comparison", "Line-level difference statistics", "Character-level highlighting"],
  },
  {
    id: "word-counter",
    name: "Word & Character Counter",
    route: "word-counter",
    toolPath: "text-utilities",
    endpoint: "#count",
    favicon: "favicon-word-counter.svg",
    description: "Count words, characters, sentences, paragraphs, and estimated LLM tokens, with reading time and word frequency.",
    capabilities: ["Word, character, line, and sentence counts", "GPT-style token estimate", "Reading time and word frequency"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    route: "unit-converter",
    description: "Convert common measurements across length, area, volume, mass, temperature, time, speed, data, and more.",
    capabilities: ["Multiple measurement categories", "Instant bidirectional conversion", "US, UK, metric, and digital units"],
  },
  {
    id: "url-parser",
    name: "URL Parser",
    route: "url-parser",
    description: "Break a URL into its scheme, host, port, path, query, and fragment, edit the query parameters in a table, and rebuild the URL without changing what you didn't touch.",
    capabilities: ["Lossless URL breakdown into components", "Editable query-parameter table", "Normalized URL, punycode host, and encoding checks"],
  },
].map((tool) => Object.freeze({
  ...tool,
  toolPath: tool.toolPath || tool.id,
  endpoint: tool.endpoint || "",
  favicon: tool.favicon || "favicon.svg",
  aliases: Object.freeze((tool.aliases || []).map((alias) => Object.freeze({ ...alias }))),
})));
