globalThis.DEV_TOOLS_CATALOG = Object.freeze([
  {
    id: "base-converter",
    name: "Base Converter",
    route: "base-converter",
    description: "Convert UTF-8 text and byte values between binary, hexadecimal, decimal, and octal representations instantly in your browser.",
    capabilities: ["UTF-8 text and byte conversion", "Binary, hexadecimal, decimal, and octal output", "Live bidirectional conversion"],
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    route: "chmod-calculator",
    description: "Build Unix file permissions from a checkbox grid and read the octal, symbolic, chmod command, and umask defaults at once.",
    capabilities: ["Octal, symbolic, and checkbox editing", "Ready-to-run chmod and umask commands", "Plain-English reading with risk warnings"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    route: "color-converter",
    description: "Convert colours between HEX, RGB, HSL, and OKLCH and check any pair against the WCAG contrast thresholds, entirely in your browser.",
    capabilities: ["HEX, RGB, HSL, and OKLCH conversion", "WCAG AA and AAA contrast ratios", "Alpha compositing and sRGB gamut warnings"],
  },
  {
    id: "cron-expression-generator",
    name: "Cron Expression Generator",
    route: "cron-expression-generator",
    description: "Build, parse, and explain cron expressions in plain English, then preview the next scheduled run times in any time zone.",
    capabilities: ["Plain-English schedule explanation", "Next run times in any time zone", "Per-field editor with common presets"],
  },
  {
    id: "crypto-generator",
    name: "Crypto Generator",
    route: "crypto-generator",
    description: "Generate cryptographically secure random values and developer-friendly credentials locally with your browser's security APIs.",
    capabilities: ["Cryptographically secure randomness", "Developer-friendly output formats", "Local browser generation"],
  },
  {
    id: "encoder-decoder",
    name: "Encoder / Decoder",
    route: "encoder-decoder",
    description: "Encode and decode text with Base64, Base64url, URL percent-encoding, and HTML entities locally in your browser.",
    capabilities: ["Base64 and Base64url encoding", "URL component and full-URL escaping", "HTML entity escaping and unescaping"],
  },
  {
    id: "fake-data-generator",
    name: "Fake Data Generator",
    route: "fake-data-generator",
    description: "Design a schema and generate realistic JSON test records with names, addresses, IDs, dates, numbers, and nested fields.",
    capabilities: ["Visual schema builder", "Realistic test-data fields", "Flat and nested JSON records"],
  },
  {
    id: "file-compressor",
    name: "File Compressor",
    route: "file-compressor",
    description: "Compress files locally in your browser with multiple algorithms while comparing original and compressed sizes before download.",
    capabilities: ["Multiple compression formats", "Before-and-after size comparison", "Local file processing"],
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    route: "html-preview",
    description: "Write HTML, CSS, and JavaScript in a live browser playground with an instant preview and downloadable output.",
    capabilities: ["Live HTML, CSS, and JavaScript editing", "Instant isolated preview", "Downloadable result"],
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    route: "http-status-codes",
    description: "Search every HTTP status code with plain-English meanings, when-to-use guidance, common mistakes, and the RFC that defines it.",
    capabilities: ["Searchable 1xx-5xx reference", "When to use and what to avoid", "RFC references and related codes"],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    route: "image-converter",
    description: "Convert PNG, JPEG, WebP, SVG, and BMP images locally, control output quality, and optionally remove standard metadata.",
    capabilities: ["Automatic source-format detection", "PNG, JPEG, and WebP output", "Optional metadata stripping"],
  },
  {
    id: "id-generator",
    name: "ID Generator",
    route: "id-generator",
    description: "Generate and inspect developer identifiers including UUID variants and ULIDs directly in your browser.",
    capabilities: ["Multiple UUID versions", "ULID generation", "Identifier decoding and inspection"],
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    route: "json-diff",
    description: "Compare two JSON documents with formatting, validation, and clear structural difference highlighting.",
    capabilities: ["Side-by-side JSON comparison", "Syntax validation and formatting", "Structural difference highlighting"],
  },
  {
    id: "json-toon-converter",
    name: "JSON to Toon Converter",
    route: "json-toon-converter",
    toolPath: "json-toon-converter",
    endpoint: "#json-toon",
    favicon: "favicon-json-toon.svg",
    description: "Convert standard JSON data into compact Toon format locally with validation and copy-ready output.",
    capabilities: ["JSON-to-Toon conversion", "Input validation", "Copy-ready formatted output"],
  },
  {
    id: "json-xml-converter",
    name: "JSON to XML Converter",
    route: "json-to-xml-converter",
    toolPath: "json-xml-converter",
    endpoint: "#json-xml",
    favicon: "favicon-json-xml.svg",
    description: "Convert JSON documents into formatted XML locally with validation and convenient editing controls.",
    capabilities: ["JSON-to-XML conversion", "Syntax validation", "Formatted XML output"],
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    route: "jwt-debugger",
    description: "Decode, inspect, edit, and verify JSON Web Tokens with readable header, payload, signature, and timestamp details.",
    capabilities: ["JWT header and payload decoding", "Signature verification tools", "Claim and timestamp inspection"],
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    route: "lorem-ipsum-generator",
    toolPath: "text-utilities",
    endpoint: "#lorem",
    favicon: "favicon-lorem.svg",
    description: "Generate lorem ipsum placeholder paragraphs, sentences, words, or list items locally and count them as you go.",
    capabilities: ["Paragraph, sentence, word, and list output", "Classic Lorem ipsum opening", "Instant word and character counts"],
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    route: "markdown-editor",
    description: "Write Markdown with synchronized editing, safe live preview, local file opening, and export-friendly controls.",
    capabilities: ["Safe live Markdown preview", "Local file opening", "Synchronized editor experience"],
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    route: "qr-generator",
    description: "Create customizable QR codes for links, contact details, Wi-Fi, email, phone, UPI, and other common formats.",
    capabilities: ["Multiple QR content types", "Customizable output", "Downloadable QR codes"],
  },
  {
    id: "regex-cheatsheet",
    name: "Regex Cheat Sheet",
    route: "regex-cheatsheet",
    description: "A JavaScript regex reference with syntax, flags, lookaround, and a library of tested patterns for email, URL, UUID, and more.",
    capabilities: ["Searchable ECMAScript syntax reference", "Tested pattern library with samples", "One-click handover to the Regex Tester"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    route: "regex-tester",
    description: "Test regular expressions with live match highlighting, flags, capture details, navigation, and replacement templates.",
    capabilities: ["Live regular-expression matches", "Flag and capture-group controls", "Replacement output templates"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    route: "sql-formatter",
    description: "Format and beautify SQL queries locally with readable indentation and practical editor controls.",
    capabilities: ["SQL formatting and beautification", "Readable indentation", "Local query processing"],
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    route: "text-cleaner",
    toolPath: "text-utilities",
    endpoint: "#clean",
    description: "Trim, sort, deduplicate, renumber, and recase lines of text locally with a predictable, ordered pipeline.",
    capabilities: ["Trim, collapse, and drop empty lines", "Sort, reverse, shuffle, and deduplicate", "Upper, lower, title, and sentence case"],
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    route: "timestamp-converter",
    description: "Convert Unix timestamps to ISO 8601, human-readable and relative time across time zones, and back again, entirely in your browser.",
    capabilities: ["Unix seconds, milliseconds and microseconds", "ISO 8601, RFC 1123 and relative time", "Time zone and DST aware conversion"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    route: "text-diff",
    description: "Compare text side by side with added, removed, modified, and character-level differences clearly highlighted.",
    capabilities: ["Side-by-side text comparison", "Line-level difference statistics", "Character-level highlighting"],
  },
  {
    id: "toon-json-converter",
    name: "Toon to JSON Converter",
    route: "toon-to-json-converter",
    toolPath: "json-toon-converter",
    endpoint: "#toon-json",
    favicon: "favicon-toon-json.svg",
    description: "Convert Toon data into standard formatted JSON locally with validation and copy-ready output.",
    capabilities: ["Toon-to-JSON conversion", "Input validation", "Formatted JSON output"],
  },
  {
    id: "word-counter",
    name: "Word & Character Counter",
    route: "word-counter",
    toolPath: "text-utilities",
    endpoint: "#count",
    favicon: "favicon-word-counter.svg",
    description: "Count words, characters, sentences, paragraphs, and estimated LLM tokens, with reading time and word frequency.",
    capabilities: ["Word, character, line, and sentence counts", "GPT-style token estimate", "Reading time and word frequency"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    route: "unit-converter",
    description: "Convert common measurements across length, area, volume, mass, temperature, time, speed, data, and more.",
    capabilities: ["Multiple measurement categories", "Instant bidirectional conversion", "US, UK, metric, and digital units"],
  },
  {
    id: "xml-json-converter",
    name: "XML to JSON Converter",
    route: "xml-to-json-converter",
    toolPath: "json-xml-converter",
    endpoint: "#xml-json",
    favicon: "favicon-xml-json.svg",
    description: "Convert XML documents into readable JSON locally with validation and convenient formatting controls.",
    capabilities: ["XML-to-JSON conversion", "Syntax validation", "Formatted JSON output"],
  },
].map((tool) => Object.freeze({
  ...tool,
  toolPath: tool.toolPath || tool.id,
  endpoint: tool.endpoint || "",
  favicon: tool.favicon || "favicon.svg",
})));
