globalThis.DEV_TOOLS_CATALOG = Object.freeze([
  {
    id: "base-converter",
    name: "Base Converter",
    route: "base-converter",
    description: "Convert UTF-8 text and byte values between binary, hexadecimal, decimal, and octal representations instantly in your browser.",
    capabilities: ["UTF-8 text and byte conversion", "Binary, hexadecimal, decimal, and octal output", "Live bidirectional conversion"],
  },
  {
    id: "crypto-generator",
    name: "Crypto Generator",
    route: "crypto-generator",
    description: "Generate cryptographically secure random values and developer-friendly credentials locally with your browser's security APIs.",
    capabilities: ["Cryptographically secure randomness", "Developer-friendly output formats", "Local browser generation"],
  },
  {
    id: "fake-data-generator",
    name: "Fake Data Generator",
    route: "fake-data-generator",
    description: "Design a schema and generate realistic JSON test records with names, addresses, IDs, dates, numbers, and nested fields.",
    capabilities: ["Visual schema builder", "Realistic test-data fields", "Flat and nested JSON records"],
  },
  {
    id: "file-compressor",
    name: "File Compressor",
    route: "file-compressor",
    description: "Compress files locally in your browser with multiple algorithms while comparing original and compressed sizes before download.",
    capabilities: ["Multiple compression formats", "Before-and-after size comparison", "Local file processing"],
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    route: "html-preview",
    description: "Write HTML, CSS, and JavaScript in a live browser playground with an instant preview and downloadable output.",
    capabilities: ["Live HTML, CSS, and JavaScript editing", "Instant isolated preview", "Downloadable result"],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    route: "image-converter",
    description: "Convert PNG, JPEG, WebP, SVG, and BMP images locally, control output quality, and optionally remove standard metadata.",
    capabilities: ["Automatic source-format detection", "PNG, JPEG, and WebP output", "Optional metadata stripping"],
  },
  {
    id: "id-generator",
    name: "ID Generator",
    route: "id-generator",
    description: "Generate and inspect developer identifiers including UUID variants and ULIDs directly in your browser.",
    capabilities: ["Multiple UUID versions", "ULID generation", "Identifier decoding and inspection"],
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    route: "json-diff",
    description: "Compare two JSON documents with formatting, validation, and clear structural difference highlighting.",
    capabilities: ["Side-by-side JSON comparison", "Syntax validation and formatting", "Structural difference highlighting"],
  },
  {
    id: "json-toon-converter",
    name: "JSON to Toon Converter",
    route: "json-toon-converter",
    toolPath: "json-toon-converter",
    endpoint: "#json-toon",
    favicon: "favicon-json-toon.svg",
    description: "Convert standard JSON data into compact Toon format locally with validation and copy-ready output.",
    capabilities: ["JSON-to-Toon conversion", "Input validation", "Copy-ready formatted output"],
  },
  {
    id: "json-xml-converter",
    name: "JSON to XML Converter",
    route: "json-to-xml-converter",
    toolPath: "json-xml-converter",
    endpoint: "#json-xml",
    favicon: "favicon-json-xml.svg",
    description: "Convert JSON documents into formatted XML locally with validation and convenient editing controls.",
    capabilities: ["JSON-to-XML conversion", "Syntax validation", "Formatted XML output"],
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    route: "jwt-debugger",
    description: "Decode, inspect, edit, and verify JSON Web Tokens with readable header, payload, signature, and timestamp details.",
    capabilities: ["JWT header and payload decoding", "Signature verification tools", "Claim and timestamp inspection"],
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    route: "markdown-editor",
    description: "Write Markdown with synchronized editing, safe live preview, local file opening, and export-friendly controls.",
    capabilities: ["Safe live Markdown preview", "Local file opening", "Synchronized editor experience"],
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    route: "qr-generator",
    description: "Create customizable QR codes for links, contact details, Wi-Fi, email, phone, UPI, and other common formats.",
    capabilities: ["Multiple QR content types", "Customizable output", "Downloadable QR codes"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    route: "regex-tester",
    description: "Test regular expressions with live match highlighting, flags, capture details, navigation, and replacement templates.",
    capabilities: ["Live regular-expression matches", "Flag and capture-group controls", "Replacement output templates"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    route: "sql-formatter",
    description: "Format and beautify SQL queries locally with readable indentation and practical editor controls.",
    capabilities: ["SQL formatting and beautification", "Readable indentation", "Local query processing"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    route: "text-diff",
    description: "Compare text side by side with added, removed, modified, and character-level differences clearly highlighted.",
    capabilities: ["Side-by-side text comparison", "Line-level difference statistics", "Character-level highlighting"],
  },
  {
    id: "toon-json-converter",
    name: "Toon to JSON Converter",
    route: "toon-to-json-converter",
    toolPath: "json-toon-converter",
    endpoint: "#toon-json",
    favicon: "favicon-toon-json.svg",
    description: "Convert Toon data into standard formatted JSON locally with validation and copy-ready output.",
    capabilities: ["Toon-to-JSON conversion", "Input validation", "Formatted JSON output"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    route: "unit-converter",
    description: "Convert common measurements across length, area, volume, mass, temperature, time, speed, data, and more.",
    capabilities: ["Multiple measurement categories", "Instant bidirectional conversion", "US, UK, metric, and digital units"],
  },
  {
    id: "xml-json-converter",
    name: "XML to JSON Converter",
    route: "xml-to-json-converter",
    toolPath: "json-xml-converter",
    endpoint: "#xml-json",
    favicon: "favicon-xml-json.svg",
    description: "Convert XML documents into readable JSON locally with validation and convenient formatting controls.",
    capabilities: ["XML-to-JSON conversion", "Syntax validation", "Formatted JSON output"],
  },
].map((tool) => Object.freeze({
  ...tool,
  toolPath: tool.toolPath || tool.id,
  endpoint: tool.endpoint || "",
  favicon: tool.favicon || "favicon.svg",
})));
