/* Regex reference data — JavaScript (ECMAScript) flavour.
 *
 * Everything here is written for the engine that actually runs in a browser
 * and in Node. Where another flavour differs in a way that bites (\A, atomic
 * groups, possessive quantifiers), the note says so rather than pretending
 * JavaScript has it.
 *
 * Every pattern in PATTERNS is asserted against its own `good` and `bad`
 * samples by the test suite, so a copy-pasted pattern does what the card says.
 */

globalThis.REGEX_CHEATSHEET = Object.freeze([
  {
    id: "characters",
    title: "Character classes",
    rows: [
      { token: ".", meaning: "Any character except a line break (any character at all with the `s` flag).", example: "/a.c/ matches \"abc\", \"a-c\"" },
      { token: "\\d  \\D", meaning: "A digit 0-9; `\\D` is anything that is not a digit.", example: "/\\d{4}/ matches \"2026\"" },
      { token: "\\w  \\W", meaning: "A word character: [A-Za-z0-9_]. Not Unicode-aware — \"é\" is not \\w.", example: "/\\w+/ matches \"user_1\"" },
      { token: "\\s  \\S", meaning: "Whitespace: space, tab, newline, and Unicode spaces.", example: "/\\s+/ matches the gap in \"a  b\"" },
      { token: "[abc]", meaning: "Any one of the listed characters.", example: "/[aeiou]/ matches a vowel" },
      { token: "[^abc]", meaning: "Any one character that is not listed. The caret only negates inside brackets.", example: "/[^0-9]/ matches a non-digit" },
      { token: "[a-z]", meaning: "A range. Combine freely: [A-Za-z0-9_-].", example: "/[a-f0-9]{6}/ matches \"3fa9c2\"" },
      { token: "\\p{L}  \\P{L}", meaning: "Unicode property. Requires the `u` or `v` flag. \\p{L} is any letter in any script.", example: "/\\p{L}+/u matches \"naïve\", \"日本語\"" },
      { token: "[\\s\\S]", meaning: "Any character including newlines — the portable way to say \"everything\" without the `s` flag.", example: "/<div>[\\s\\S]*?<\\/div>/" },
    ],
  },
  {
    id: "anchors",
    title: "Anchors and boundaries",
    rows: [
      { token: "^", meaning: "Start of the string, or start of a line with the `m` flag.", example: "/^Error/m finds each line starting with Error" },
      { token: "$", meaning: "End of the string, or end of a line with the `m` flag.", example: "/;$/m flags lines ending in a semicolon" },
      { token: "\\b", meaning: "A word boundary — the seam between \\w and non-\\w. Zero width.", example: "/\\bcat\\b/ matches \"cat\" but not \"concatenate\"" },
      { token: "\\B", meaning: "Not a word boundary.", example: "/\\Bcat/ matches the \"cat\" inside \"concat\"" },
      { token: "\\A  \\z  \\Z", meaning: "Absolute string anchors in PCRE, Python and Ruby — JavaScript has none of them. Use ^ and $ without the `m` flag.", example: "Not supported in JavaScript" },
    ],
  },
  {
    id: "quantifiers",
    title: "Quantifiers",
    rows: [
      { token: "*", meaning: "Zero or more. Greedy: takes as much as it can, then backs off.", example: "/ab*/ matches \"a\", \"abbb\"" },
      { token: "+", meaning: "One or more.", example: "/\\d+/ matches \"42\"" },
      { token: "?", meaning: "Zero or one — makes the previous token optional.", example: "/colou?r/ matches both spellings" },
      { token: "{n}", meaning: "Exactly n times.", example: "/\\d{4}/ matches exactly four digits" },
      { token: "{n,}", meaning: "n or more times.", example: "/\\d{2,}/ matches two digits or more" },
      { token: "{n,m}", meaning: "Between n and m times. No space after the comma — /a{1, 3}/ is a literal.", example: "/\\d{2,4}/ matches 2 to 4 digits" },
      { token: "*?  +?  ??  {n,m}?", meaning: "Lazy versions: take as little as possible. The usual fix for a greedy match swallowing the rest of the line.", example: "/\".*?\"/ matches one quoted string, not everything between the first and last quote" },
      { token: "*+  ++  (?>…)", meaning: "Possessive quantifiers and atomic groups exist in PCRE, Java and Ruby but not in JavaScript. The `v` flag does not add them.", example: "Not supported in JavaScript" },
    ],
  },
  {
    id: "groups",
    title: "Groups, alternation and references",
    rows: [
      { token: "(x)", meaning: "Capturing group — numbered left to right by its opening parenthesis.", example: "/(\\d{4})-(\\d{2})/ captures year and month" },
      { token: "(?:x)", meaning: "Non-capturing group. Use it whenever you only need the grouping, so your capture numbers stay stable.", example: "/(?:https?:\\/\\/)?example\\.com/" },
      { token: "(?<name>x)", meaning: "Named capture. Read it from `match.groups.name` — far more readable than counting parentheses.", example: "/(?<year>\\d{4})/ then match.groups.year" },
      { token: "\\1  \\k<name>", meaning: "Backreference: match the same text the group captured.", example: "/(\\w+) \\1/ finds a doubled word" },
      { token: "|", meaning: "Alternation. It has the lowest precedence, so group it: /^(cat|dog)$/, not /^cat|dog$/.", example: "/(GET|POST|PUT)/" },
    ],
  },
  {
    id: "lookaround",
    title: "Lookaround",
    rows: [
      { token: "(?=x)", meaning: "Lookahead: the next text must match, but is not consumed.", example: "/\\d+(?= USD)/ matches \"20\" in \"20 USD\"" },
      { token: "(?!x)", meaning: "Negative lookahead: the next text must not match. The standard way to express \"must contain\" rules.", example: "/^(?!.*admin).*$/ rejects anything containing \"admin\"" },
      { token: "(?<=x)", meaning: "Lookbehind. Supported in every current browser and in Node since v9.", example: "/(?<=\\$)\\d+/ matches \"30\" in \"$30\"" },
      { token: "(?<!x)", meaning: "Negative lookbehind.", example: "/(?<!\\$)\\b\\d+/ skips numbers preceded by a dollar sign" },
    ],
  },
  {
    id: "flags",
    title: "Flags",
    rows: [
      { token: "g", meaning: "Global — find every match instead of stopping at the first. Also makes `lastIndex` stateful; see the traps below.", example: "text.replace(/a/g, \"b\")" },
      { token: "i", meaning: "Case-insensitive.", example: "/error/i matches \"ERROR\"" },
      { token: "m", meaning: "Multiline: ^ and $ match at line breaks. It does not change what `.` matches.", example: "/^\\s*#/m finds comment lines" },
      { token: "s", meaning: "Dot-all: `.` also matches newlines.", example: "/<body>.*<\\/body>/s" },
      { token: "u", meaning: "Unicode mode: enables \\p{…}, \\u{…} and correct handling of astral characters such as emoji.", example: "/\\u{1F600}/u matches 😀" },
      { token: "y", meaning: "Sticky: match only at `lastIndex`, never search forward. Useful for tokenisers.", example: "Lexers that must not skip unexpected input" },
      { token: "d", meaning: "Indices: adds `match.indices` with the start and end of every group.", example: "/(\\w+)/d then match.indices[1]" },
      { token: "v", meaning: "Unicode sets (2023): set operations inside classes, such as [\\p{L}--\\p{Lu}] for lowercase letters only.", example: "/[\\p{Script=Greek}&&\\p{Letter}]/v" },
    ],
  },
  {
    id: "escapes",
    title: "Escapes and literals",
    rows: [
      { token: ". * + ? ^ $ { } ( ) | [ ] \\ /", meaning: "The characters you must escape with a backslash to match literally.", example: "/\\$\\d+\\.\\d{2}/ matches \"$9.99\"" },
      { token: "\\n  \\t  \\r", meaning: "Newline, tab, carriage return.", example: "/\\r?\\n/ matches a line break on either platform" },
      { token: "\\uFFFF  \\u{1F600}", meaning: "A code unit, or a full code point with the `u` flag.", example: "/\\u00e9/ matches \"é\"" },
      { token: "\\xFF", meaning: "A character by two-digit hex code.", example: "/\\x41/ matches \"A\"" },
      { token: "RegExp.escape", meaning: "Escapes user input for safe use in a pattern (2025; not yet everywhere). Until then: str.replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\").", example: "new RegExp(escaped)" },
    ],
  },
  {
    id: "replacement",
    title: "Replacement strings",
    rows: [
      { token: "$&", meaning: "The whole match.", example: "\"abc\".replace(/b/, \"[$&]\") → \"a[b]c\"" },
      { token: "$1  $2", meaning: "The text of capture group 1, 2 …", example: "/(\\d+)-(\\d+)/ with \"$2-$1\" swaps the halves" },
      { token: "$<name>", meaning: "A named group's text.", example: "\"$<year>-$<month>\"" },
      { token: "$$", meaning: "A literal dollar sign.", example: "\"$$$1\" prefixes a currency symbol" },
      { token: "$`  $'", meaning: "Everything before, and everything after, the match.", example: "Rarely worth the confusion" },
      { token: "(m, p1) => …", meaning: "A replacer function gets the match and each group, so any logic at all can decide the replacement.", example: "s.replace(/\\d+/g, n => Number(n) * 2)" },
    ],
  },
  {
    id: "traps",
    title: "Traps worth knowing",
    rows: [
      { token: "lastIndex with /g", meaning: "A regex literal with `g` or `y` keeps state between calls. `re.test(x)` twice on the same string can return true then false. Build the regex inside the loop, or reset `re.lastIndex = 0`.", example: "const re = /a/g; re.test(\"a\") → true; re.test(\"a\") → false" },
      { token: "Catastrophic backtracking", meaning: "Nested quantifiers over overlapping character sets — /(a+)+$/ — can take exponential time on a non-matching string. That is a denial of service if the input is user-supplied.", example: "Avoid (x+)+ , (x*)* and (a|a)* shapes" },
      { token: "Parsing HTML", meaning: "Nested, optional and self-closing tags are not a regular language. Use DOMParser for HTML and a real parser for JSON; regex is for scanning, not structure.", example: "new DOMParser().parseFromString(html, \"text/html\")" },
      { token: "\\w and \\d are ASCII", meaning: "In JavaScript these never include accented letters or other scripts, even with the `u` flag. Use \\p{L} and \\p{Nd} when input can be non-English.", example: "/^\\p{L}+$/u instead of /^\\w+$/" },
      { token: "Anchors without m", meaning: "`^` and `$` cover the whole string by default, so a multi-line input fails validation you expected to pass — or worse, /^\\d+$/ accepts \"12\\n\" in some engines. In JavaScript `$` does not match before a trailing newline, but many other languages' \\Z does.", example: "Validate a single line, or use the `m` flag deliberately" },
      { token: "Escaping user input", meaning: "Interpolating raw user text into `new RegExp()` lets them inject pattern syntax — at best a crash, at worst a backtracking bomb.", example: "Always escape before interpolating" },
    ],
  },
]);

globalThis.REGEX_PATTERNS = Object.freeze([
  /* --- Web and network --------------------------------------------------- */
  {
    id: "email",
    name: "Email address (pragmatic)",
    category: "Web",
    pattern: "^[^\\s@]+@[^\\s@.]+\\.[^\\s@]{2,}$",
    flags: "",
    description: "Accepts anything with one @ and a dotted domain. Deliberately loose.",
    note: "No regex validates email correctly — RFC 5322 allows quoted strings and comments, and a syntactically perfect address can still bounce. Use this to catch typos, then send a confirmation email to actually verify.",
    good: ["dev@example.com", "first.last+tag@sub.example.co.uk"],
    bad: ["no-at-sign.com", "two@@example.com", "trailing@dot."],
  },
  {
    id: "url-http",
    name: "HTTP/HTTPS URL",
    category: "Web",
    pattern: "^https?:\\/\\/[^\\s/$.?#].[^\\s]*$",
    flags: "i",
    description: "An absolute http or https URL with no whitespace.",
    note: "For anything beyond a sanity check use `new URL(value)` in a try/catch — it handles ports, credentials, IDN and percent-encoding correctly.",
    good: ["https://example.com", "http://localhost:3000/path?q=1#top"],
    bad: ["ftp://example.com", "example.com", "https://"],
  },
  {
    id: "domain",
    name: "Domain name",
    category: "Web",
    pattern: "^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$",
    flags: "",
    description: "A hostname with at least two labels, rejecting labels that start or end with a hyphen.",
    note: "Punycode domains (xn--…) pass; raw Unicode domains do not — convert with `URL` first.",
    good: ["example.com", "sub.example.co.uk", "xn--bcher-kva.example"],
    bad: ["example", "-bad.com", "bad-.com", "exa mple.com"],
  },
  {
    id: "ipv4",
    name: "IPv4 address",
    category: "Web",
    pattern: "^((25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)\\.){3}(25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)$",
    flags: "",
    description: "Four octets, each genuinely limited to 0-255.",
    note: "Rejects leading zeros such as 192.168.001.1, which some parsers read as octal.",
    good: ["0.0.0.0", "192.168.1.1", "255.255.255.255"],
    bad: ["256.1.1.1", "1.2.3", "192.168.001.1", "1.2.3.4.5"],
  },
  {
    id: "ipv6",
    name: "IPv6 address",
    category: "Web",
    pattern: "^(([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|([0-9A-Fa-f]{1,4}:){1,7}:|([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4}|([0-9A-Fa-f]{1,4}:){1,5}(:[0-9A-Fa-f]{1,4}){1,2}|([0-9A-Fa-f]{1,4}:){1,4}(:[0-9A-Fa-f]{1,4}){1,3}|([0-9A-Fa-f]{1,4}:){1,3}(:[0-9A-Fa-f]{1,4}){1,4}|([0-9A-Fa-f]{1,4}:){1,2}(:[0-9A-Fa-f]{1,4}){1,5}|[0-9A-Fa-f]{1,4}:(:[0-9A-Fa-f]{1,4}){1,6}|:((:[0-9A-Fa-f]{1,4}){1,7}|:))$",
    flags: "",
    description: "Full and compressed forms, including :: elision.",
    note: "Does not cover IPv4-mapped forms (::ffff:192.0.2.1) or zone indexes (%eth0). IPv6 is a good example of a pattern better handled by a parser.",
    good: ["2001:0db8:85a3:0000:0000:8a2e:0370:7334", "2001:db8::8a2e:370:7334", "::1", "::"],
    bad: ["2001:db8", "gggg::1", "1.2.3.4"],
  },
  {
    id: "port",
    name: "Port number",
    category: "Web",
    pattern: "^(6553[0-5]|655[0-2]\\d|65[0-4]\\d{2}|6[0-4]\\d{3}|[1-5]\\d{4}|[1-9]\\d{0,3})$",
    flags: "",
    description: "1 to 65535, with no leading zeros.",
    note: "Excludes 0, which is valid in some APIs as \"pick any free port\".",
    good: ["80", "8080", "65535"],
    bad: ["0", "65536", "99999", "08"],
  },
  {
    id: "mac",
    name: "MAC address",
    category: "Web",
    pattern: "^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$",
    flags: "",
    description: "Six hex pairs separated by colons or hyphens.",
    note: "Does not accept the Cisco dotted form (0011.2233.4455).",
    good: ["00:1B:44:11:3A:B7", "00-1b-44-11-3a-b7"],
    bad: ["00:1B:44:11:3A", "001B44113AB7", "00:1B:44:11:3A:ZZ"],
  },
  {
    id: "slug",
    name: "URL slug",
    category: "Web",
    pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    flags: "",
    description: "Lowercase words joined by single hyphens — no leading, trailing or doubled hyphens.",
    note: "To produce one: text.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-+|-+$/g, \"\").",
    good: ["hello-world", "regex-cheat-sheet-2026", "a"],
    bad: ["Hello-World", "-leading", "double--hyphen", "trailing-"],
  },

  /* --- Identifiers -------------------------------------------------------- */
  {
    id: "uuid",
    name: "UUID (any version)",
    category: "Identifiers",
    pattern: "^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[1-8][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$",
    flags: "",
    description: "A canonical RFC 9562 UUID, versions 1-8, with a valid variant nibble.",
    note: "Use [0-9A-Fa-f]{4} in the third group instead of [1-8]… if you must accept the nil UUID or non-conforming ids.",
    good: ["123e4567-e89b-12d3-a456-426614174000", "01912d68-783e-7b3c-9f2a-1a2b3c4d5e6f"],
    bad: ["123e4567e89b12d3a456426614174000", "123e4567-e89b-02d3-a456-426614174000", "not-a-uuid"],
  },
  {
    id: "ulid",
    name: "ULID",
    category: "Identifiers",
    pattern: "^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    flags: "",
    description: "26 characters of Crockford base32, sortable by time.",
    note: "The alphabet deliberately omits I, L, O and U to avoid transcription errors.",
    good: ["01ARZ3NDEKTSV4RRFFQ69G5FAV", "7ZZZZZZZZZZZZZZZZZZZZZZZZZ"],
    bad: ["01ARZ3NDEKTSV4RRFFQ69G5FAI", "01arz3ndektsv4rrffq69g5fav", "TOOSHORT"],
  },
  {
    id: "semver",
    name: "Semantic version",
    category: "Identifiers",
    pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$",
    flags: "",
    description: "The official semver.org pattern, with named parts for prerelease and build metadata.",
    note: "Rejects a leading \"v\" — strip it first. Also rejects leading zeros in any numeric part, as the spec requires.",
    good: ["1.0.0", "2.11.3-beta.1", "1.0.0-rc.1+build.123"],
    bad: ["v1.0.0", "1.0", "01.0.0"],
  },
  {
    id: "jwt",
    name: "JWT",
    category: "Identifiers",
    pattern: "^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]*$",
    flags: "",
    description: "Three base64url segments; the signature may be empty for an unsigned token.",
    note: "Shape only — it proves nothing about the signature. Verify the token properly before trusting a claim.",
    good: ["eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk", "eyJhbGciOiJub25lIn0.eyJzdWIiOiIxIn0."],
    bad: ["not.a", "a.b.c.d", "has spaces.in.it"],
  },
  {
    id: "hex-color",
    name: "Hex colour",
    category: "Identifiers",
    pattern: "^#(?:[0-9A-Fa-f]{3,4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$",
    flags: "",
    description: "Three, four, six or eight hex digits — the short forms include the alpha variants.",
    good: ["#fff", "#FFCC00", "#11223344"],
    bad: ["fff", "#ff", "#12345", "#gggggg"],
  },
  {
    id: "base64",
    name: "Base64",
    category: "Identifiers",
    pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$",
    flags: "",
    description: "Standard base64 with correct padding and a length that is a multiple of four.",
    note: "For base64url swap +/ for -_ and drop the padding.",
    good: ["aGVsbG8=", "aGVsbG8gd29ybGQ=", "YWJjZA=="],
    bad: ["aGVsbG8", "aGVsbG8===", "###"],
  },

  /* --- Dates, times and numbers ------------------------------------------- */
  {
    id: "iso-date",
    name: "ISO 8601 date",
    category: "Dates & numbers",
    pattern: "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
    flags: "",
    description: "YYYY-MM-DD with month and day ranges enforced.",
    note: "Does not know that 2026-02-30 is not a real date — check with Date after the shape passes.",
    good: ["2026-09-21", "1999-12-31"],
    bad: ["2026-13-01", "2026-9-21", "26-09-21"],
  },
  {
    id: "iso-datetime",
    name: "ISO 8601 date-time",
    category: "Dates & numbers",
    pattern: "^\\d{4}-\\d{2}-\\d{2}[Tt]\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?([Zz]|[+-]\\d{2}:\\d{2})$",
    flags: "",
    description: "A full timestamp with fractional seconds and a mandatory offset or Z.",
    note: "Requiring the offset is the point: a timestamp without one is ambiguous.",
    good: ["2026-09-21T10:30:00Z", "2026-09-21T10:30:00.123+05:30"],
    bad: ["2026-09-21T10:30:00", "2026-09-21 10:30:00Z"],
  },
  {
    id: "time-24h",
    name: "24-hour time",
    category: "Dates & numbers",
    pattern: "^([01]\\d|2[0-3]):[0-5]\\d(:[0-5]\\d)?$",
    flags: "",
    description: "HH:MM with optional seconds, 00:00 to 23:59:59.",
    good: ["00:00", "09:30", "23:59:59"],
    bad: ["24:00", "9:30", "12:60"],
  },
  {
    id: "integer",
    name: "Integer",
    category: "Dates & numbers",
    pattern: "^[+-]?(0|[1-9]\\d*)$",
    flags: "",
    description: "An optionally signed integer with no leading zeros.",
    good: ["0", "42", "-17", "+8"],
    bad: ["007", "1.5", "1e3", ""],
  },
  {
    id: "decimal",
    name: "Decimal number",
    category: "Dates & numbers",
    pattern: "^[+-]?(\\d+(\\.\\d+)?|\\.\\d+)$",
    flags: "",
    description: "A plain decimal, with or without a leading digit.",
    note: "Add (?:[eE][+-]?\\d+)? at the end to allow scientific notation.",
    good: ["3.14", "-0.5", ".5", "42"],
    bad: ["1.2.3", "1,5", "1e3"],
  },
  {
    id: "currency",
    name: "Currency amount",
    category: "Dates & numbers",
    pattern: "^[$£€₹]?\\s?\\d{1,3}(,\\d{3})*(\\.\\d{2})?$",
    flags: "",
    description: "An optional symbol, thousands separators, and exactly two decimals when present.",
    note: "Grouping is not universal — Indian numbering groups as 1,00,000 and much of Europe swaps the separators.",
    good: ["$1,234.56", "₹500", "1,000", "€ 99.00"],
    bad: ["$1,23.456", "1,0000", "$1.5"],
  },
  {
    id: "percentage",
    name: "Percentage 0-100",
    category: "Dates & numbers",
    pattern: "^(100(\\.0+)?|\\d{1,2}(\\.\\d+)?)%?$",
    flags: "",
    description: "0 to 100 with optional decimals and an optional percent sign.",
    good: ["0", "99.9%", "100", "100.00"],
    bad: ["101", "-5", "1000"],
  },

  /* --- People and places --------------------------------------------------- */
  {
    id: "phone-e164",
    name: "Phone number (E.164)",
    category: "People & places",
    pattern: "^\\+[1-9]\\d{7,14}$",
    flags: "",
    description: "The international storage format: a plus, a country code, and up to 15 digits total.",
    note: "Normalise to E.164 by stripping everything except digits and the leading plus. For real validation use a library with per-country rules.",
    good: ["+919876543210", "+14155552671"],
    bad: ["+0123456789", "919876543210", "+1 415 555 2671"],
  },
  {
    id: "phone-us",
    name: "Phone number (US, loose)",
    category: "People & places",
    pattern: "^(\\+?1[\\s.-]?)?\\(?([2-9]\\d{2})\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$",
    flags: "",
    description: "Accepts the common written forms, with or without the country code.",
    good: ["(415) 555-2671", "415-555-2671", "+1 415.555.2671"],
    bad: ["155-5267", "(015) 555-2671"],
  },
  {
    id: "phone-in",
    name: "Mobile number (India)",
    category: "People & places",
    pattern: "^(?:\\+91[\\s-]?|0)?[6-9]\\d{9}$",
    flags: "",
    description: "Ten digits starting 6-9, with an optional +91 or leading zero.",
    good: ["9876543210", "+91 9876543210", "09876543210"],
    bad: ["5876543210", "98765432", "+91 5876543210"],
  },
  {
    id: "zip-us",
    name: "ZIP code (US)",
    category: "People & places",
    pattern: "^\\d{5}(-\\d{4})?$",
    flags: "",
    description: "Five digits, optionally with the ZIP+4 extension.",
    good: ["94103", "94103-1234"],
    bad: ["9410", "941031234"],
  },
  {
    id: "pin-in",
    name: "PIN code (India)",
    category: "People & places",
    pattern: "^[1-9]\\d{5}$",
    flags: "",
    description: "Six digits; the first is never zero.",
    good: ["110001", "560034"],
    bad: ["011001", "11001"],
  },
  {
    id: "postcode-uk",
    name: "Postcode (UK)",
    category: "People & places",
    pattern: "^[A-Z]{1,2}\\d[A-Z\\d]?\\s?\\d[A-Z]{2}$",
    flags: "i",
    description: "The standard outward and inward code pair.",
    note: "Deliberately loose — the official rules exclude certain letters in certain positions.",
    good: ["SW1A 1AA", "M1 1AE", "ec1a1bb"],
    bad: ["SW1A", "123 456"],
  },
  {
    id: "username",
    name: "Username",
    category: "People & places",
    pattern: "^[a-zA-Z0-9](?:[a-zA-Z0-9._-]{1,28}[a-zA-Z0-9])?$",
    flags: "",
    description: "3-30 characters, starting and ending alphanumeric, with dots, hyphens and underscores inside.",
    note: "Also allows 1 character; tighten the bound if you need a minimum length.",
    good: ["dev", "jane.doe", "user_01-x"],
    bad: [".leading", "trailing_", "has space", "way-too-long-username-value-here"],
  },
  {
    id: "password-strong",
    name: "Strong password rule",
    category: "People & places",
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\w\\s]).{12,}$",
    flags: "",
    description: "At least 12 characters with a lowercase letter, an uppercase letter, a digit and a symbol — four lookaheads, each independent of position.",
    note: "Length beats composition: NIST now recommends long passphrases and screening against breached lists rather than character-class rules. Never cap length, and never block paste.",
    good: ["Tr0ub4dor&3xyz", "correct-Horse1!"],
    bad: ["password", "Short1!", "alllowercase1!"],
  },

  /* --- Text, code and logs -------------------------------------------------- */
  {
    id: "trim",
    name: "Leading and trailing whitespace",
    category: "Text & code",
    pattern: "^\\s+|\\s+$",
    flags: "gm",
    description: "Matches the whitespace to strip. Replace with an empty string; `m` handles every line.",
    note: "For a single string, String.prototype.trim() is faster and clearer.",
    good: ["  padded", "padded  "],
    bad: ["no-padding"],
  },
  {
    id: "collapse-spaces",
    name: "Repeated whitespace",
    category: "Text & code",
    pattern: "[^\\S\\r\\n]{2,}",
    flags: "g",
    description: "Two or more spaces or tabs, without touching line breaks. Replace with a single space.",
    note: "[^\\S\\r\\n] is the idiom for \"whitespace that is not a newline\" — a double negative, but the only concise way to say it.",
    good: ["a    b", "tab\t\tseparated"],
    bad: ["single space"],
  },
  {
    id: "blank-lines",
    name: "Blank lines",
    category: "Text & code",
    pattern: "^\\s*$\\n?",
    flags: "gm",
    description: "Empty or whitespace-only lines, including the line break. Replace with an empty string to compact a file.",
    good: ["\n\n", "   \n"],
    bad: ["content"],
  },
  {
    id: "duplicate-word",
    name: "Doubled word",
    category: "Text & code",
    pattern: "\\b(\\w+)\\s+\\1\\b",
    flags: "gi",
    description: "The same word twice in a row — the classic backreference example, and a genuinely useful proofreading pass.",
    good: ["the the cat", "a A duplicate"],
    bad: ["the cat", "cat category"],
  },
  {
    id: "js-comment",
    name: "JavaScript comment",
    category: "Text & code",
    pattern: "\\/\\*[\\s\\S]*?\\*\\/|\\/\\/.*",
    flags: "g",
    description: "Block and line comments. The lazy `*?` stops the block form at the first close.",
    note: "It will also match comment-looking text inside a string literal. Stripping comments properly needs a tokenizer.",
    good: ["// a note", "/* multi\nline */"],
    bad: ["const url = 1;"],
  },
  {
    id: "html-tag",
    name: "HTML tag",
    category: "Text & code",
    pattern: "<\\/?([a-zA-Z][\\w-]*)\\b[^>]*>",
    flags: "g",
    description: "One opening or closing tag, capturing the tag name.",
    note: "Fine for scanning or stripping tags; useless for anything structural. Comments, CDATA and attributes containing \">\" all break it.",
    good: ["<div class=\"a\">", "</p>", "<br/>"],
    bad: ["plain text", "a < b"],
  },
  {
    id: "markdown-link",
    name: "Markdown link",
    category: "Text & code",
    pattern: "\\[([^\\]]+)\\]\\(([^)\\s]+)(?:\\s+\"([^\"]*)\")?\\)",
    flags: "g",
    description: "Captures the text, the URL and the optional title.",
    note: "Nested brackets inside the link text will end the match early.",
    good: ["[docs](https://example.com)", "[x](./a.md \"Title\")"],
    bad: ["[no link]", "(just parens)"],
  },
  {
    id: "hashtag",
    name: "Hashtag",
    category: "Text & code",
    pattern: "(?<=^|\\s)#(\\p{L}[\\p{L}\\p{N}_]*)",
    flags: "gu",
    description: "A hashtag at a word start, Unicode-aware so non-English tags work.",
    note: "The lookbehind stops it matching the fragment in a URL or a CSS colour.",
    good: ["#regex", "start #日本語"],
    bad: ["#1", "https://x.com/#anchor"],
  },
  {
    id: "ansi-escape",
    name: "ANSI escape code",
    category: "Text & code",
    pattern: "\\u001B\\[[0-9;]*[A-Za-z]",
    flags: "g",
    description: "Terminal colour and cursor codes. Replace with an empty string to clean captured CLI output.",
    good: ["\u001B[31m", "\u001B[0m", "\u001B[1;32m"],
    bad: ["[31m plain"],
  },
  {
    id: "file-extension",
    name: "File extension",
    category: "Text & code",
    pattern: "\\.([A-Za-z0-9]+)$",
    flags: "",
    description: "The last extension on a filename, captured without the dot.",
    note: "Matches \"gz\" in archive.tar.gz — use /\\.(tar\\.)?[a-z0-9]+$/i when the double extension matters.",
    good: ["report.pdf", "archive.tar.gz"],
    bad: ["Makefile", "trailing."],
  },
  {
    id: "query-param",
    name: "Query string parameter",
    category: "Text & code",
    pattern: "[?&]([^=&#]+)=([^&#]*)",
    flags: "g",
    description: "Each key and value in a query string.",
    note: "URLSearchParams does this correctly, including repeated keys and percent-decoding. Reach for the regex only when you have a URL-shaped string that is not a URL.",
    good: ["?a=1&b=2", "/x?q=regex#frag"],
    bad: ["plain/path"],
  },
  {
    id: "camel-to-snake",
    name: "camelCase boundary",
    category: "Text & code",
    pattern: "([a-z0-9])([A-Z])",
    flags: "g",
    description: "The seam inside a camelCase word. Replace with \"$1_$2\" and lowercase the result to get snake_case.",
    good: ["userName", "parseHTTPResponse"],
    bad: ["username", "USER_NAME"],
  },
  {
    id: "log-line",
    name: "Timestamped log line",
    category: "Text & code",
    pattern: "^(?<time>\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2})\\s+\\[?(?<level>TRACE|DEBUG|INFO|WARN|ERROR|FATAL)\\]?\\s+(?<message>.*)$",
    flags: "gim",
    description: "Splits a conventional log line into named time, level and message groups.",
    note: "Named groups make the result readable: match.groups.level.",
    good: ["2026-09-21 10:30:00 ERROR Database timeout", "2026-09-21T10:30:00 [warn] Retrying"],
    bad: ["Something happened"],
  },
  {
    id: "emoji",
    name: "Emoji",
    category: "Text & code",
    pattern: "\\p{Extended_Pictographic}",
    flags: "gu",
    description: "Any pictographic character, using a Unicode property instead of a hand-written code-point range.",
    note: "A single visible emoji can be several code points (skin tones, ZWJ families), so counting matches is not counting emoji. Use Intl.Segmenter for that.",
    good: ["🙂", "ship it 🚀"],
    bad: ["plain text", ":-)"],
  },
]);
