// Curated common types; registry: https://www.iana.org/assignments/media-types/
globalThis.MIME_TYPES = [
  ["html htm", "text/html", "HTML document; escape untrusted content."],
  ["css", "text/css", "Stylesheet; serve as CSS, not text/plain."],
  ["js mjs", "text/javascript", "JavaScript module or script."],
  ["json map", "application/json", "JSON uses UTF-8; comments are not JSON."],
  [
    "xml",
    "application/xml",
    "XML document; encoding must match its declaration.",
  ],
  ["txt log", "text/plain", "Plain text; specify charset when needed."],
  ["csv", "text/csv", "Delimited text; quoting matters."],
  ["md markdown", "text/markdown", "Markdown source, not rendered HTML."],
  ["yaml yml", "application/yaml", "YAML data."],
  ["pdf", "application/pdf", "PDF document."],
  ["png", "image/png", "Lossless raster with alpha."],
  ["jpg jpeg jpe", "image/jpeg", "Lossy raster; no alpha channel."],
  ["webp", "image/webp", "WebP raster, animation and alpha support."],
  ["avif", "image/avif", "AV1 image format."],
  ["gif", "image/gif", "Indexed colour and animation."],
  [
    "svg svgz",
    "image/svg+xml",
    "SVG can contain active content; do not trust arbitrary inline SVG. SVGZ also needs gzip Content-Encoding.",
  ],
  ["ico", "image/vnd.microsoft.icon", "Windows icon format."],
  ["bmp", "image/bmp", "Bitmap image."],
  ["tif tiff", "image/tiff", "Tagged image format."],
  ["woff", "font/woff", "Web font."],
  ["woff2", "font/woff2", "Compressed web font."],
  ["ttf", "font/ttf", "TrueType font."],
  ["otf", "font/otf", "OpenType font."],
  ["mp3", "audio/mpeg", "MPEG audio."],
  ["wav", "audio/wav", "Common WAV type; some servers use audio/x-wav."],
  ["ogg oga", "audio/ogg", "Ogg audio container."],
  ["opus", "audio/ogg", "Opus is commonly carried in an Ogg container."],
  ["mp4 m4v", "video/mp4", "MPEG-4 video container; codecs vary."],
  ["webm", "video/webm", "WebM video container."],
  ["ogv", "video/ogg", "Ogg video."],
  [
    "zip",
    "application/zip",
    "ZIP archive; distinct from HTTP Content-Encoding.",
  ],
  [
    "gz gzip",
    "application/gzip",
    "Gzip file; use Content-Encoding when compressing an HTTP representation instead.",
  ],
  ["tar", "application/x-tar", "Common tar archive type."],
  ["7z", "application/x-7z-compressed", "7-Zip archive."],
  [
    "wasm",
    "application/wasm",
    "WebAssembly; required for streaming compilation.",
  ],
  ["bin exe dll", "application/octet-stream", "Generic binary fallback."],
  [
    "",
    "application/x-www-form-urlencoded",
    "Form key-value body; percent-encode values.",
  ],
  [
    "",
    "multipart/form-data",
    "Form uploads require a matching boundary parameter.",
  ],
  ["ics", "text/calendar", "Calendar data."],
  ["epub", "application/epub+zip", "EPUB publication."],
  [
    "docx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "Word document.",
  ],
  [
    "xlsx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "Excel workbook.",
  ],
  [
    "pptx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "PowerPoint presentation.",
  ],
];
